### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by taichikitano** [taichikitano/furima-39758#23]
# URL
https://furima-39758.onrender.com
# Basic認証
ID: admin
pass: 2222
# 出品用テストユーザー
email: test@test
pass: 111111a
# 購入用テストユーザー
email: test@testtest
pass: 111111a

**Comment by snkw-works** [comment]
@taichikitano さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！ **LGTM** です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）

[補足]
トップページの「人生を変えるフリマアプリ」の背景画像が表示されておりません。
こちらは必須要件ではございませんが、修正して頂くことでより完成度の高いアプリになります。

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)

**Comment by taichikitano** [comment]
LGTMありがとうございます。
トップページの背景画像が表示されるように修正いたしましたので、
issueクローズとさせていただきます。
